### ISSUE TITLE
Print view of markdown files

### ISSUE THREAD

**Issue by ftrojahn** [haiwen/seahub#244]
In seafile's modern web interface it's really comfortable to show/edit Markdown documents. 

But there's no print button - when trying print preview in browser, the full Seafile interface surrounds the document, making printing of the document itself impossible.

I'd suggest to include in e.g. media/css/file_view_extra.css something like this:

```css
@media print {
  #header, #view-hd, #view-path-op, #file-op, #file-enc-cont, #bottom-bar {
	display: none; 
  }
  #file-view {
	padding:0;
  }
  #md-view {
	border: none;
	padding: 0; 
	width: 100%;
  }
}

```

thanx anyway for your great work!
