### ISSUE TITLE
After v11 Update: CSRF Failed: Origin checking failed

### ISSUE THREAD

**Issue by pr4xx** [haiwen/seahub#5633]
I just updated my 10 server to version 11. Now, whenever I use the web interface to do something API related like `DELETE https://sub.domain.com/api/v2.1/upload-links/a8b55d9c08dd46cbbe73/`, I get a 403 error: 

`CSRF Failed: Origin checking failed - https://sub.domain.com does not match any trusted origins.`

I cannot find a way to configure the trusted origin list.

I use the docker setup with traefik as the primary web server. So no internal HTTPS and LetsEncrypt.
This is my docker compose config:

```
seafile:
    image: seafileltd/seafile-mc:11.0.0
    container_name: seafile
    restart: always
    expose:
      - 80
    volumes:
      - seafile:/shared
    networks:
      - traefik
      - web
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=<password>
      - TIME_ZONE=Europe/Berlin
      - SEAFILE_ADMIN_EMAIL=<email>
      - SEAFILE_ADMIN_PASSWORD=<password>
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=sub.domain.com
     labels:
      - traefik.enable=true
      - traefik.http.routers.seafile.rule=Host(`sub.domain.com`)
      - traefik.http.routers.seafile.entrypoints=websecure
      - traefik.http.routers.seafile.tls.certresolver=myresolver
      - traefik.docker.network=traefik
```
